jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        Binovo\ElkarBackupBundle\Entity\User: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        administrators:
            entity: { class: BinovoElkarBackupBundle:User, property: username }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js|setlocale)/
            security: false

        login:
            pattern:  ^/login$
            security: false

        publickey:
            pattern: ^/config/publickey/get$
            security: false

        #runjob:
        #    pattern: ^/client/[0-9]+/job/[0-9]+/run
        #    security: false

        secured_area:
            pattern:    ^/
            anonymous:  true
            form_login:
                check_path: /login_check
                login_path: /login
            logout:
                path:   /logout
                target: /

    access_control:
        - { path: ^/login                        , roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/config/publickey/get         , roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/client/[0-9]+/job/[0-9]+/run , roles: IS_AUTHENTICATED_ANONYMOUSLY}
        - { path: ^/user                         , roles: ROLE_ADMIN}
        - { path: ^/users                        , roles: ROLE_ADMIN}
        - { path: ^/config/params                , roles: ROLE_ADMIN}
        - { path: ^/config/repositorybackupscript, roles: ROLE_ADMIN}
        - { path: ^/config/publickey/generate    , roles: ROLE_ADMIN}
        - { path: ^/                             , roles: ROLE_USER}
