<?php
/**
 * @copyright 2012,2013 Binovo it Human Project, S.L.
 * @license http://www.opensource.org/licenses/bsd-license.php New-BSD
 */

namespace Application\Migrations;

use Doctrine\DBAL\Migrations\AbstractMigration,
    Doctrine\DBAL\Schema\Schema;
use Binovo\ElkarBackupBundle\Lib\Globals;

/**
 * Auto-generated Migration: Please modify to your need!
 */
class Version20130306101349 extends AbstractMigration
{
    public function up(Schema $schema)
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

        $maxId = 0;
        foreach (scandir(Globals::getUploadDir()) as $script) {
            $matches = array();
            if (preg_match('/^([0-9]{4})[.]script$/', $script, $matches)) {
                $maxId = max($maxId, (int)$matches[1]);
            }
        }
    }

    public function down(Schema $schema)
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() != "mysql");

    }
}
